### PR TITLE
8261752: Multiple GC test are missing memory requirements

### PR DESCRIPTION
**Pull request by mychris**
---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8261752](https://bugs.openjdk.java.net/browse/JDK-8261752): Multiple GC test are missing memory requirements

### Reviewers
 * [Aleksey Shipilev](https://openjdk.java.net/census#shade) (@shipilev - **Reviewer**)

### Download
`$ git fetch https://git.openjdk.java.net/jdk16u pull/33/head:pull/33`
`$ git checkout pull/33`

### CODE REVIEW

**Comment by shipilev** [comment]
Note: you have requested `jdk16-fix-request`, not "u". I changed it for you.

**Review by shipilev — APPROVED** [review]
The backport looks good. You still need to wait for `jdk16u-fix-yes` in JIRA.

**Comment by mychris** [comment]
Oh, thanks a lot for looking into this and fixing the tag, didn't notice this.

**Comment by shipilev** [comment]
Please check you have the approval tag on the issue (I think you have), and if so, say `/integrate`, and I shall sponsor.

**Comment by mychris** [comment]
Yes, you are right, it got approved.
Thanks for sponsoring.
/integrate

**Pull request closed without merging**
