### PR TITLE
8261483: jdk/dynalink/TypeConverterFactoryMemoryLeakTest.java failed with "AssertionError: Should have GCd a method handle by now"

### PR DESCRIPTION
**Pull request by szegedi**
Backporting this to eliminate flakiness of tests

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8261483](https://bugs.openjdk.java.net/browse/JDK-8261483): jdk/dynalink/TypeConverterFactoryMemoryLeakTest.java failed with "AssertionError: Should have GCd a method handle by now"

### Reviewers
 * [Aleksey Shipilev](https://openjdk.java.net/census#shade) (@shipilev - **Reviewer**)

### Download
`$ git fetch https://git.openjdk.java.net/jdk16u pull/68/head:pull/68`
`$ git checkout pull/68`

### CODE REVIEW

**Comment by szegedi** [comment]
The only reason this didn't get the "clean" label is that in 16u these tests were never put on the `test/jdk/ProblemList.txt` so the changes to that file don't apply here.

**Review by shipilev — APPROVED** [review]
Looks fine. You still need to wait for `jdk16u-fix-yes` in JIRA.

**Comment by shipilev** [comment]
I think you are good to go? There seems to be `jdk16u-fix-yes` in JIRA. `16.0.1` integration window closes this week.

**Pull request closed without merging**
